# Generated by Django 3.1.1 on 2020-11-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0017_booking_user1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=10, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
