# Generated by Django 3.1.1 on 2020-11-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0018_cinema'),
    ]

    operations = [
        migrations.AddField(
            model_name='set_timing',
            name='name1',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
