# Generated by Django 3.1.1 on 2020-11-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0019_set_timing_name1'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='revstars',
            field=models.IntegerField(max_length=2, null=True),
        ),
    ]
